---

- name: Add lines to sysconfig/d-s-s
  lineinfile:
    create: true
    backup: False
    dest: "/etc/sysconfig/docker-storage-setup"
    line: "{{ item }}"
  with_items: '{{ sysconfig_dss_lines }}'

- name: Add lines to sysconfig/d-s-s latest
  lineinfile:
    create: true
    backup: False
    dest: "/etc/sysconfig/docker-latest-storage-setup"
    line: "{{ item }}"
  with_items: '{{ sysconfig_dss_lines }}'

# Necessary so docker / docker-latest service properly runs d-s-s
- name: The /var/lib/docker and docker-latest directories are empty
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/var/lib/docker"
    - "/var/lib/docker-latest"
