---

docker_autotest_templates:
    - src: "{{ custom_subtests_ini_j2 | default('subtests.ini.j2') }}"
      dest: "{{ autotest_docker_path }}/config_custom/subtests.ini"
    - src: "{{ custom_control_ini_j2 | default('control.ini.j2') }}"
      dest: "{{ autotest_docker_path }}/config_custom/control.ini"

docker_autotest:
    test_image:
        host: "localhost"
        user: ""
        name: "fedora_python"
        tag: "latest"
        build_url: "https://raw.githubusercontent.com/cevich/autotest-docker-enabled-product-testing/devel/files/fedora_test_image.tar.gz"
    preserve_fqins:
        - "fedora_python:latest"
        - "docker.io/fedora:latest"
    preserve_cnames: []
    execute: true
    enable_bugzilla: true
