---
- name: Test image host is optional
  set_fact:
    test_image_host: ''
  when: autotest_docker.test_image is defined and
        autotest_docker.test_image.host is defined and
        autotest_docker.test_image.host == None

- name: Test image host is defined
  set_fact:
    test_image_host: "{{ autotest_docker.test_image.host }}"
  when: test_image_host is not defined

- name: Test image user is optional
  set_fact:
    test_image_user: ''
  when: autotest_docker.test_image is defined and
        autotest_docker.test_image.user is defined and
        autotest_docker.test_image.user == None

- name: Test image user is defined
  set_fact:
    test_image_user: "{{ autotest_docker.test_image.user }}"
  when: test_image_user is not defined

- name: Test image tag is optional
  set_fact:
    test_image_tag: 'latest'
  when: autotest_docker.test_image is defined and
        autotest_docker.test_image.tag is defined and
        autotest_docker.test_image.tag == None

- name: Test image tag is defined
  set_fact:
    test_image_tag: "{{ autotest_docker.test_image.tag }}"
  when: test_image_tag is not defined

- name: Docker Autotest test image known in fqin format
  set_fact:
    test_image_fqin: "{{ test_image_host }}/{{ test_image_user }}/{{ autotest_docker.test_image.name }}:{{ test_image_tag }}"
  when: autotest_docker.test_image is defined and
        autotest_docker.test_image.name is defined and
        autotest_docker.test_image.name != None

- name: Docker Autotest test image was previously built
  command: /usr/bin/docker inspect --format \{\{.Created\}\}
           {{ test_image_fqin }}
  register: docker_inspect_result
  ignore_errors: True
  args:
    warn: no
  changed_when: false
  when: test_image_fqin is defined

- name: Build Test Image
  command: /usr/bin/docker run
           {{ docker.build_args }}
           {{ docker.build_fqin }}
           --workdir /host/{{ autotest_docker_path }}
           /usr/bin/docker build
           --quiet
           --tag {{ test_image_fqin }}
           {{ autotest_docker.test_image.build_url }}
  when: test_image_fqin is defined and
        autotest_docker.test_image is defined and
        autotest_docker.test_image.build_url is defined and
        autotest_docker.test_image.build_url != None and
        docker_inspect_result|failed
