---

- name: runtime job-specific workspace location is buffered
  set_fact:
    kommandir_workspace: '{{ kommandir_workspaces }}/{{ adept_job }}'

# Skip all partitioning/formatting steps if fs already mounted
- name: findmnt command is run, ignoring exit code
  command: findmnt {{ kommandir_workspaces }}
  register: findmnt
  ignore_errors: True

- include: setup_workspaces.yml
  when: findmnt | failed

- name: runtime job-specific workspace directory is created
  file:
    path: '{{ kommandir_workspace }}'
    state: directory

