---

# Depends:
#   installed_rpms: list
#   installed_enablerepo: list
#   installed_disablerepo: list
#   use_dnf: optional - boolean
#   state: present/latest
# Registers:
#   rpms_installed: boolean
#   needs_reboot: boolean

- block:

    # Allows re-use by 'updated' role
    - name: installed_rpms defaults to ''
      set_fact:
        _installed_rpms: "{{ installed_rpms }}"
      when: installed_rpms is undefined or installed_rpms == None or
            installed_rpms == [] or installed_rpms == ""

    # Allows re-use by 'updated' role
    - name: state defaults to "present"
      set_fact:
        state: "present"
      when: state is undefined or state == None or
            state == [] or state == ""

- block:

    # Defines repo_csv
    - include: roles/common/tasks/repo_csv.yml
      vars:
        repo_list: '{{ installed_enablerepo | default([]) }}'

    - name: enablerepo buffer set
      set_fact:
        _enablerepo: '{{ repo_csv }}'

    - include: roles/common/tasks/repo_csv.yml
      vars:
        repo_list: '{{ installed_disablerepo | default([]) }}'

    - name: disablerepo buffer set
      set_fact:
        _disablerepo: '{{ repo_csv }}'

- block:

    - name: RPMs are installed with yum
      yum:
        name: "{{ _installed_rpms | join(',') }}"
        state: "{{ state }}"
        enablerepo: '{{ _enablerepo }}'
        disablerepo: '{{ _disablerepo }}'
      register: rpms_installed

  when: _installed_rpms != '' and not use_dnf

- block:

    - name: RPMs are installed with dnf
      dnf:
        name: "{{ _installed_rpms | join(',') }}"
        state: "{{ state }}"
        enablerepo: '{{ _enablerepo }}'
        disablerepo: '{{ _disablerepo }}'
      register: rpms_installed

  when: _installed_rpms != '' and use_dnf

- name: rpms_installed and needs_reboot are defined
  set_fact:
    rpms_installed: "{{ rpms_installed | changed }}"
    needs_reboot: "{{ rpms_installed | changed }}"
