---

- name: All repositories are disabled
  command: /usr/sbin/subscription-manager repos --disable=*

- name: Support packages are installed
  yum:
  args:
    name: docker-io*,atomic,procps,tar,findutils,bzip2,gdb,bridge-utils,nfs-utils,git,glibc-devel,python-bugzilla,which
    state: present
    enablerepo: "{{ enabled_repos }}"
  register: support_installed
  notify:
    - The needs_reboot flag is set because of install or package update

- name: System is fully updated
  yum:
  args:
     name: "*"
     state: latest
     enablerepo: "{{ enabled_repos }}"
  register:
    system_updated
  notify:
    - The needs_reboot flag is set because of install or package update
  when: update_system

- include: ../../common/site_scripts.yml.inc
