---

- include: ../../common/site_scripts.yml.inc

- name: Support packages are installed with yum
  yum:
    name: "{{ install_rpms }}"
    state: present
  register: support_installed
  notify:
    - The needs_reboot flag is set because of install or package update
  when: ansible_distribution_major_version < 22

- name: Support packages are installed with dnf
  dnf:
    name: "{{ install_rpms }}"
    state: present
  register: support_installed
  notify:
    - The needs_reboot flag is set because of install or package update
  when: ansible_distribution_major_version > 21

- name: System is fully updated with yum
  yum:
    name: "*"
    state: latest
  register:
    system_updated
  notify:
    - The needs_reboot flag is set because of install or package update
  when: update_system and ansible_distribution_major_version < 22

- name: System is fully updated with dnf
  dnf:
    name: "*"
    state: latest
  register:
    system_updated
  notify:
    - The needs_reboot flag is set because of install or package update
  when: update_system and ansible_distribution_major_version > 21
