---

enable_repos:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
    - rhel-7-server-optional-rpms
    - rhel-7-server-supplementary-rpms
install_rpms:
    - docker
    - docker-latest
    - atomic
    - docker-selinux
    - procps
    - tar
    - lvm2
    - findutils
    - bzip2
    - gdb
    - bridge-utils
    - nfs-utils
    - git
    - glibc-devel
    - which
    - cloud-utils-growpart
    - selinux-policy-targeted
    - libselinux-python
    - iputils
