---
- debug: var=docker_autotest.timeout
  when: docker_autotest.timeout is defined

- name: Control timeout set
  lineinfile:
  args:
    backrefs: true
    dest: "{{ autotest_docker_path }}/control"
    follow: True
    line: "\\1 {{ docker_autotest_timeout }}"
    regexp: "^(TIMEOUT\\s*=\\s*).*$"
  when: docker_autotest.timeout is defined

- name: Config_custom_control string is set
  set_fact:
    config_custom_control: "{{ autotest_docker_path }}/config_custom/control.ini"

- name: Custom control file status is known
  stat:
  args:
    path: "{{ config_custom_control }}"
  register: config_custom_control

- name: Control needed flag is set true
  set_fact:
    control_needed: true
  when: not config_custom_control.stat.exists

- name: Control needed flag is set false
  set_fact:
    control_needed: false
  when: control_needed is not defined

- name: Copy control
  command: cp config_defaults/control.ini config_custom/control.ini
  args:
    chdir: "{{ autotest_docker_path }}"
  when: control_needed

- name: Control is configured for included tests
  ini_file:
  args:
    dest: "{{ autotest_docker_path }}/config_custom/control.ini"
    option: include
    section: Control
    value: '{{ docker_autotest.include | join(",") }}'
  when: control_needed and
        docker_autotest.include is defined and
        docker_autotest.include != None

- name: Control is configured for excluded tests
  ini_file:
  args:
    dest: "{{ autotest_docker_path }}/config_custom/control.ini"
    option: exclude
    section: Control
    value: '{{ docker_autotest.exclude | join(",") }}'
  when: control_needed and
        docker_autotest.exclude is defined and
        docker_autotest.exclude != None

- name: Control is configured for pre/intra/post/sub-tests to run
  ini_file:
  args:
    dest: "{{ autotest_docker_path }}/config_custom/control.ini"
    option: subthings
    section: Control
    value: '{{ docker_autotest.subthings | join(",") }}'
  when: control_needed and
        docker_autotest.subthings is defined and
        docker_autotest.subthings != None

- name: Control bugzilla checking is disabled
  ini_file:
  args:
    dest: "{{ autotest_docker_path }}/config_custom/control.ini"
    option: url
    section: Bugzilla
    value: ''
  when: control_needed and
        docker_autotest.enable_bugzilla is defined and
        docker_autotest.enable_bugzilla != None and
        not docker_autotest.enable_bugzilla
