---
- name: All is_<release> flags are initialized false
  set_fact:
    is_rhel: false
    is_rhelah: false
    is_centos: false
    is_fedora: false

- name: The redhat_release canonical name is initialized empty
  set_fact:
    redhat_release:

- name: The /etc/redhat-release contents are known
  command: cat /etc/redhat-release
  register: redhat_release_contents
  changed_when: False

- name: The redhat_release value contains no parenthetical value.
  set_fact:
    redhat_release: "{{ redhat_release_contents.stdout
                        | regex_replace('\\s+\\(.+\\)', '') }}"

- name: The redhat_release value contains no 'release' or version number
  set_fact:
    redhat_release: "{{ redhat_release
                        | regex_replace('\\s+release\\s+.+$', '') }}"

- name: A RHEL Atomic Host redhat_release is processed
  set_fact: is_rhelah=true release_name=rhelah
  when: redhat_release | match('.*Atomic Host.*')

- name: A RHEL Server redhat_release is processed
  set_fact: is_rhel=true release_name=rhel
  when: not is_rhelah and
        redhat_release | match('.*Red Hat Enterprise Linux.*')

- name: A CentOS redhat_release is processed
  set_fact: is_centos=true release_name=centos
  when: redhat_release | match('.*CentOS.*')

- name: A Fedora redhat_release is processed
  set_fact: is_fedora=true release_name=fedora
  when: redhat_release | match('.*Fedora.*')

- group_by: key={{ release_name }}

- debug:
    msg: "is_rhel={{ is_rhel }}; is_rhelah={{ is_rhelah }}; is_centos={{ is_centos }}; is_fedora={{ is_fedora }}; release_name={{ release_name }}; group_names={{ group_names }}"

- name: At least one is_<release> flag is set
  assert:
    that: is_rhel or is_rhelah or is_centos or is_fedora
