---

host_groups:
    - fedora
    - docker  # this is docker-latest

peon_image: 'Fedora-Cloud-25'

peon_size: '20'

peon_flavor: 'm1.medium'

peon_userdata: '{{ workspace }}/roles/peon_created/files/nodocker_userdata.yml'
