---

ansible_shell_type: sh

peon_groups:
    - openstack
    - fedoratomic
    - updated
    - docker
    - autotested

peon_image: 'Fedora-Atomic-26'

peon_flavor: 'm1.medium'

peon_userdata: '{{ workspace }}/roles/peon_created/files/nodocker_userdata.yml'
