---

ansible_shell_type: sh

host_groups:
    - rhelatomic
    - docker-latest

peon_image: 'rhel-atomic-cloud-7.4-released-latest'

peon_flavor: 'm1.medium'

peon_userdata: '{{ workspace }}/roles/peon_created/files/nodocker_userdata.yml'
