---

host_groups:
    - rhel
    - docker

peon_image: 'rhel-7.2-server-x86_64-released'

peon_size: '20'

peon_flavor: 'm1.medium'

peon_userdata: '{{ workspace }}/roles/peon_created/files/nodocker_userdata.yml'
