---

peon_groups:
    - openstack
    - rhel
    - subscribed
    - updated
    - docker-latest
    - autotested

peon_image: 'rhel-7.3-server-x86_64-latest'

peon_size: '20'

peon_flavor: 'm1.medium'

peon_userdata: '{{ workspace }}/roles/peon_created/files/nodocker_userdata.yml'
