---

- name: System is registered and subscribed
  redhat_subscription:
  args:
    autosubscribe: True
    username: "{{ rhsm.username }}"
    password: "{{ rhsm.password }}"
    rhsm_baseurl: "{{ rhsm.baseurl | default(omit) }}"
    server_hostname: "{{ rhsm.hostname | default(omit) }}"
    insecure: "{{ rhsm.insecure | default(omit) }}"
    state: present
  register: result
  until: result | success
  retries: "{{ rhsm_retries }}"
  delay: "{{ rhsm_delay }}"
  when: rhsm.username is defined and
        rhsm.username != [] and
        rhsm.password is defined and
        rhsm.password != []
