---

# rhsm_baseurl/server_hostname only modify configuration in
# redhat_subscription module.  More reliable to just pass on
# the command-line directly
- name: System is registered and subscribed
  shell: >
    subscription-manager register\
                         --username=$RHSM_USERNAME\
                         --password=$RHSM_PASSWORD\
                         --auto-attach\
                         {% if rhsm.insecure | default(False) %}--insecure {%- endif %}\
                         {% if rhsm.baseurl | default(False) %}--baseurl={{ rhsm.baseurl }} {%- endif %}\
                         {% if rhsm.hostname | default(False) %}--serverurl={{ rhsm.hostname }} {%- endif %}
  environment:
    RHSM_USERNAME: "{{ rhsm.username }}"
    RHSM_PASSWORD: "{{ rhsm.password }}"
  register: result
  when: rhsm.username is defined and
        rhsm.username != [] and
        rhsm.password is defined and
        rhsm.password != []
  until: result | success
  retries: "{{ rhsm_retries | default(omit) }}"
  delay: "{{ rhsm_delay | default(omit) }}"

- debug: var=result
