---

use_dnf: False
installed_enablerepo:
    - base
    - extras
    - updates
installed_rpms:
    - docker
    - atomic
    - docker-selinux
    - procps
    - tar
    - findutils
    - bzip2
    - gdb
    - lvm2
    - bridge-utils
    - nfs-utils
    - git
    - glibc-devel
    - which
    - cloud-utils-growpart
    - selinux-policy-targeted
    - libselinux-python
    - iputils
