---
- name: All repositories are disabled
  command: /usr/sbin/subscription-manager repos --disable=*

- include: ../../common/site_scripts.yml.inc

- name: Support packages are installed
  yum:
  args:
    name: "{{ install_rpms }}"
    state: present
    enablerepo: "{{ enabled_repos }}"
  register: support_installed
  notify:
    - The needs_reboot flag is set because of install or package update

- name: System is fully updated
  yum:
  args:
    name: "*"
    state: latest
    enablerepo: "{{ enabled_repos }}"
  register:
    system_updated
  notify:
    - The needs_reboot flag is set because of install or package update
  when: update_system
