---

# list of rsync exclusions for sensitive files not to sync out to kommandir
kommandir_sync_excludes:
    - '--exclude=.??*'
    - '--exclude=.??*/***'
    - '--exclude=**private**'
    - '--exclude=inventory/***'
    - '--exclude=AGENT_WORKSPACE'
    - '--exclude=JOB_NAME'
    - '--exclude=KMNDRIP'
    - '--exclude=KOMMANDIR_NAME'
