---

################################################################
# N/B: This may be running on an old (2.1)  version of ansible #
################################################################

# These will be updated at runtime (on a copy of this file)
ansible_host: "localhost"
ansible_ssh_host: "{{ ansible_host }}"
ansible_connection: "local"
ansible_become: false

is_atomic: False
repo_rpms:
    - epel-release
enable_repos: []
disable_repos: []
install_rpms:
    - rsync
    - iproute
    - hostname
    - sed
    - git
    - findutils
    - PyYAML
    - python-virtualenv
    - gcc
    - redhat-rpm-config
    - openssl-devel
    - libffi-devel
    - ansible

git_cache_args:
    - repo: "https://github.com/autotest/autotest.git"
      recursive: False
      cachepath: 'autotest'
    - repo: "https://github.com/autotest/autotest-docker.git"
      recursive: True
      cachepath: 'autotest-docker'
    - repo: "https://github.com/python-bugzilla/python-bugzilla.git"
      recursive: False
      cachepath: "python-bugzilla"
      version: "v1.2.2"
