---

- name: slave ansible facts written out to workspace
  copy:
    dest: "{{ workspace }}/{{ inventory_hostname }}_{{ adept_context }}_facts.yml"
    content: "{{ hostvars[inventory_hostname] | to_nice_yaml }}"

- include: roles/common/tasks/failif_lt.yml
  vars:
    lhs_version: "{{ ansible_version.full }}"
    rhs_version: "2.1"

- include: roles/slave/tasks/setup.yml
  when: adept_context == 'setup'

- include: roles/slave/tasks/run.yml
  when: adept_context == 'run'

- include: roles/slave/tasks/cleanup.yml
  when: adept_context == 'cleanup'
