---

# depends:
#   - adept_cloud_type: group name to add the slave host to
#   - ansible_force_color: true/false
#   - adept_job

- include: roles/common/tasks/workspace_file.yml
  vars:
    workspace_file: variables.yml

- fail:
    msg: "Required file {{ filepath }} does not exist"
  when: not exists

- name: variables file is loaded into buffer
  set_fact:
    _variables: '{{ lookup("file", filepath) | from_yaml }}'

- name: adept_job is hard-coded in variables to current value
  set_fact:
    _variables: '{{ _variables | combine({"adept_job": adept_job}) }}'

- name: Updated variables buffer is written to workspace file
  copy:
    dest: '{{ filepath }}'
    content: '{{ _variables | to_nice_yaml }}'
