---

# These variables apply to all hosts in the autotest_docker group
# as defaults.  To modify variables for a specific host, copy this
# file into the host_vars directory, named as the dns name
# of the host.

autotest_docker:

    # Remote directory where Autotest is installed
    autotest_dir: "/usr/local/autotest"

    # Directory containing cached autotest tree including docker autotest
    cache_dir: "../"

    # Many tests rely on a default image for testing. Specify
    # either _all_ components of the fully-qualified-image-name.
    # or no components to use defaults from docker autotest.
    test_image:
        name:
        tag:
        host:
        user:
        # Build this image from url, tagged as above name.
        # Leave empty to pull test image instead.
        build_url:

    # Ultimate timeout in seconds for all subtests to run
    # (in seconds).
    timeout: 300

    # Default timeout for individual docker commands, unless overriden
    # by specific tests.
    docker_timeout: 300

    # List of subtests to include, empty to use defaults
    # (runs _all_ specified by subthings, below).
    include:

    # List of pre/intra/post/sub-tests to exclude,
    # empty for none.
    exclude:

    # List of pre/intra/post/sub-tests to run (in order),
    # empty to run everything.
    subthings:
      - docker_cli/version
      - docker_cli/dockerhelp

    # List of subtests to exclude, empty to use defaults

    # List of template arg dictionaries use, empty for none
    # e.g. - dest: "config_custom/tests.ini"
    #        src: "tests.ini.j2"
    templates:

    # List of fqins to protect from removal during all tests
    preserve_fqins:

    # List of container names to protect from removal during all tests
    preserve_cnames:

    # Set to false to disable executing autotest on this host
    execute: true

    # Enable or disable checking of bugzilla entries for tests to skip
    enable_bugzilla: false

    # The variables below allow flexibility to dynamicly determine
    # what docker repositories, container names and versions to
    # act upon.  More than likely they do not need to be modified
    # from default values unless you know what you're doing.

    # Command to use for retrieving preserve_fqins value
    preserve_fqins_cmd: ./config_value.py DEFAULTS preserve_fqins config_defaults/defaults.ini config_custom/defaults.ini

    # Command to use for retrieving preserve_cnames value
    preserve_cnames_cmd: ./config_value.py DEFAULTS preserve_cnames config_defaults/defaults.ini config_custom/defaults.ini
