---

# Directory containing 'autotest' and 'autotest-docker' repos.
docker_autotest_cache_dir: "{{ workspace }}/cache/"

# Remote directory where Autotest will be installed
autotest_dest_dir: "/var/lib/autotest"

# Timeout in seconds to rewrite into control-file, will be divided
# equally among all subtests.
docker_autotest_timeout: "{{ docker_autotest_timeout | default(3600) }}"

# The variables below allow flexibility to dynamicly determine
# what docker repositories, container names and versions to
# preserve upon.  More than likely they do not need to be modified
# from default values unless you know what you're doing.

# Command to use for retrieving preserve_fqins value
preserve_fqins_cmd: ./config_value.py DEFAULTS preserve_fqins config_defaults/defaults.ini config_custom/defaults.ini

# Command to use for retrieving preserve_cnames value
preserve_cnames_cmd: ./config_value.py DEFAULTS preserve_cnames config_defaults/defaults.ini config_custom/defaults.ini

docker_autotest:

    # Many tests rely on a default image for testing. Specify
    # either _all_ components of the fully-qualified-image-name.
    # or no components to use defaults from docker autotest.
    test_image:
        name:
        tag:
        host:
        user:
        # Build this image from url, tagged as above name.
        # Leave empty to pull test image instead.
        build_url:

    # List of template arg dictionaries use, empty for none
    # e.g. - dest: "config_custom/tests.ini"
    #        src: "tests.ini.j2"
    templates:
        - src: "subtests.ini.j2"
          dest: "{{ autotest_docker_path }}/config_custom/subtests.ini"
        - src: "control.ini.j2"
          dest: "{{ autotest_docker_path }}/config_custom/control.ini"

    # List of fqins to protect from removal during all tests
    preserve_fqins: []

    # List of container names to protect from removal during all tests
    preserve_cnames: []

    # Set to false to disable executing autotest on this host
    execute: true

    # Set true to copy in python-bugzilla from cache directory
    enable_bugzilla: true
