---

# Depends:
#   - $WORKSPACE environment variable
#   - $ADEPT_PATH: environment variable
#   - $ADEPT_OPTIONAL (optional)
# Registers:
#   - workspace: $WORKSPACE contents or /var/lib/workspace (default)
#   - adept_path: Either $ADEPT_PATH from environment or /var/lib/adept (default)
#   - adept_optional: $ADEPT_OPTIONAL or undefined (it's optional)

- name: The WORKSPACE env. var is loaded into workspace variable
  set_fact:
    workspace: '{{ lookup("env", "WORKSPACE") | default("/var/lib/workspace", True) }}'

- name: The ADEPT_PATH env. var is loaded into adept_path variable
  set_fact:
    adept_path: '{{ lookup("env", "ADEPT_PATH") | default("/var/lib/adept", True) }}'

- name: The ADEPT_OPTIONAL env. var is buffered
  set_fact:
    adept_optional: '{{ lookup("env", "ADEPT_OPTIONAL") | trim }}'

- name: The needs_reboot flag is set false
  set_fact:
    needs_reboot: False

- include: ../../../roles/common/tasks/is_atomic.yml
- include: ../../../roles/common/tasks/is_enterprise.yml

- debug:
    var: "item"
  with_items:
    - "workspace"
    - "adept_path"
    - "adept_optional"
    - "is_atomic"
    - "is_enterprise"
