---

# Depends:
#   - kommandir_workspace
#   - kommandir_syc_excludes
#   - adept_job

# Avoid need to decode worskpace/adept_path relationship
- name: source adept path excluded temporarily
  set_fact:
    _ape:
        - "--exclude={{ adept_path }}"
        - "--update"

- name: workspace transfered to kommandir
  synchronize:
    compress: True
    dest: '{{ kommandir_workspace }}/'
    links: True
    perms: True
    owner: False
    group: False
    recursive: True
    # Copy contents to dest, not src directory itself
    src: '{{ workspace }}/'
    rsync_opts: '{{ kommandir_sync_excludes |
                    union(_ape) }}'
  # Rarely should need to debug the massive list of files
  no_log: true

# Can't assume source adept resides w/in workspace
- name: runtime job-specific adept directory exists
  file:
    path: '{{ kommandir_workspace }}/adept'
    state: directory

- name: adept transfered to kommandir
  synchronize:
    compress: True
    dest: '{{ kommandir_workspace }}/adept/'
    links: True
    perms: True
    owner: False
    group: False
    recursive: True
    # Copy contents to dest, not src directory itself
    src: '{{ adept_path }}/'
    rsync_opts: '{{ kommandir_sync_excludes |
                    union(["--update"]) }}'
  # Rarely should need to debug the massive list of files
  no_log: true

- name: ansible user owns all transfered files
  command: chown -R "{{ ansible_user_id }}.{{ ansible_user_id }}" "{{ kommandir_workspace }}"
