---
# Red Hat Subscription Manager activation credentials for test resources.
# Pull from file-contents by default, omit to bypass activation.
rhsm:
    username: "{{ lookup('file', '~/rhn_username') | default(omit) }}"
    password: "{{ lookup('file', '~/rhn_password') | default(omit) }}"
    # Set true to unsubscribe system at end of testing
    unsubscribe: false
    # Set true to ignore subscription failures
    tolerant: false
