---

- include: ../../common/site_scripts.yml.inc

- name: Atomic host is updated to latest tree
  command: atomic host upgrade
  register: atomic_host_upgrade
  notify: The needs_reboot flag is set because of install or package update
  when: update_system
  changed_when: atomic_host_upgrade.stdout | search('pgrade prepared for next boot')
  ignore_errors: true

- name: Workaround BZ1313540
  fail:
    msg: "atomic host upgrade failed with unknown error: {{ atomic_host_upgrade }}"
  when: atomic_host_upgrade.rc != 0 and atomic_host_upgrade.rc != 77
