---

# Timeout in (integer) seconds to wait for timeouts and retries.
# The default (13) comes from two DNS timeouts + one second
wait_for_timeout: 13

test_command_template: '{{ playbook_dir }}/roles/peon_up/templates/test_command.sh.j2'
