---

# Depends:
#   updated_enablerepo: list
#   updated_disablerepo: list
#   use_dnf: optional - boolean
# Registers:
#   rpms_updated: boolean
#   needs_reboot: boolean

- include: roles/installed/tasks/main.yml
  vars:
    state: "latest"
    installed_rpms: "*"

- name: rpms_updated is defined
  set_fact:
    rpms_updated: "{{ rpms_installed }}"
