---

# Depends:
#   - needs_reboot
#   - shutdown_timeout
#   - bootup_timeout
# Registers:
#   - needs_reboot

- block:

    - name: Reboot System
      shell: sleep 2 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true
      changed_when: True

    - name: System started shutting down
      wait_for:
        host: '{{ ansible_ssh_host | default(inventory_hostname) }}'
        state: stopped
        timeout: '{{ shutdown_timeout }}'
        connect_timeout: 1
      delegate_to: localhost

    - name: System has booted back up
      wait_for:
        host: '{{ ansible_host | default(inventory_hostname) }}'
        port: '{{ ansible_port | default("22") }}'
        timeout: '{{ bootup_timeout }}'
        connect_timeout: 1
      become: False
      delegate_to: localhost
      changed_when: True

    # This will exit the block
    - name: needs_reboot flag is set false
      set_fact:
        needs_reboot: False

  when: needs_reboot
